[package]
name = "todo_app"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25"
serde = { version = "1.0", features = ["derive"] }
tui = { version = "0.19.0", default-features = false, features = ["crossterm"] }  # Updated version
toml = "0.8.1"
thiserror = "1.0.40"
